// ─── MOCK DATA ────────────────────────────────────────────────────────────────
// Used while Firebase is not yet connected or for UI development.
// Replace with real Firestore queries in production.

export const MOCK_JOBS = [
  {
    id: 'j1',
    title: 'Executive Chef',
    hotelName: 'Burj Al Arab Jumeirah',
    hotelLogo: '🏨',
    country: 'ae', countryLabel: 'UAE', countryFlag: '🇦🇪',
    city: 'Dubai',
    department: 'Kitchen / Culinary',
    type: 'full-time',
    salary: { min: 3000, max: 4500, currency: 'USD', period: 'month' },
    experience: 'exec',
    hotel_category: '5-Star / Luxury',
    description: 'Lead a brigade of 60+ culinary professionals at one of the world\'s most iconic luxury hotels. Drive menu innovation, manage food costs, and maintain the highest standards of quality and presentation.',
    requirements: ['10+ years culinary experience', 'Min. 3 years as Executive Chef in 5-star property', 'HACCP Certified', 'Experience managing large teams'],
    benefits: ['Accommodation provided', 'Flight tickets', 'Medical insurance', 'Annual leave 30 days'],
    visaSponsorship: true,
    accommodationProvided: true,
    urgent: true,
    verified: true,
    postedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    applicants: 26,
    views: 340,
    status: 'active',
    employerId: 'emp1',
  },
  {
    id: 'j2',
    title: 'F&B Manager',
    hotelName: 'Marina Bay Sands',
    hotelLogo: '🏨',
    country: 'sg', countryLabel: 'Singapore', countryFlag: '🇸🇬',
    city: 'Singapore',
    department: 'F&B Service',
    type: 'full-time',
    salary: { min: 3500, max: 4800, currency: 'USD', period: 'month' },
    experience: 'senior',
    hotel_category: '5-Star / Luxury',
    description: 'Oversee all Food & Beverage operations across multiple outlets including restaurants, bars and banquets. Lead a team of 80+ associates in delivering world-class dining experiences.',
    requirements: ['5+ years F&B management', 'Strong leadership skills', 'Revenue management knowledge'],
    benefits: ['Competitive salary', 'Work visa provided', 'Medical & dental'],
    visaSponsorship: true,
    accommodationProvided: false,
    urgent: false,
    verified: true,
    postedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    applicants: 14,
    views: 210,
    status: 'active',
    employerId: 'emp2',
  },
  {
    id: 'j3',
    title: 'Banquet Supervisor',
    hotelName: 'Shangri-La Al Husn',
    hotelLogo: '🏨',
    country: 'om', countryLabel: 'Oman', countryFlag: '🇴🇲',
    city: 'Muscat',
    department: 'Banquet & Events',
    type: 'part-time',
    salary: { amount: 25, currency: 'USD', period: 'shift' },
    experience: 'mid',
    hotel_category: '5-Star / Luxury',
    shiftDate: new Date(Date.now() + 4 * 3600000).toISOString(),
    shiftTime: '6PM–12AM',
    description: 'Required for a high-profile gala dinner for 400 guests. Experienced in banquet setup, service, and team coordination.',
    requirements: ['2+ years banquet experience', 'Smart appearance', 'Available immediately'],
    benefits: ['Per-shift pay', 'Meal provided'],
    visaSponsorship: false,
    accommodationProvided: false,
    urgent: true,
    verified: true,
    postedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    applicants: 8,
    views: 145,
    status: 'active',
    employerId: 'emp3',
  },
  {
    id: 'j4',
    title: 'Front Desk Supervisor',
    hotelName: 'Marriott Marquis',
    hotelLogo: '🏨',
    country: 'sa', countryLabel: 'Saudi Arabia', countryFlag: '🇸🇦',
    city: 'Riyadh',
    department: 'Front Office',
    type: 'full-time',
    salary: { min: 1800, max: 2400, currency: 'USD', period: 'month' },
    experience: 'mid',
    hotel_category: '5-Star / Luxury',
    description: 'Manage front desk operations, lead a team of 12 receptionists, and ensure exceptional guest experience standards are maintained.',
    requirements: ['3+ years front office experience', 'Opera PMS proficiency', 'English & Arabic preferred'],
    benefits: ['Accommodation provided', 'Transportation', 'Medical insurance', 'Flight once a year'],
    visaSponsorship: true,
    accommodationProvided: true,
    urgent: false,
    verified: true,
    postedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    applicants: 31,
    views: 567,
    status: 'active',
    employerId: 'emp4',
  },
  {
    id: 'j5',
    title: 'Spa Therapist',
    hotelName: 'Mandarin Oriental Kuala Lumpur',
    hotelLogo: '🏨',
    country: 'my', countryLabel: 'Malaysia', countryFlag: '🇲🇾',
    city: 'Kuala Lumpur',
    department: 'Spa & Wellness',
    type: 'full-time',
    salary: { min: 1200, max: 1600, currency: 'USD', period: 'month' },
    experience: 'mid',
    hotel_category: '5-Star / Luxury',
    description: 'Deliver world-class spa treatments in a luxury environment. Skilled in Swedish, deep tissue, and traditional Asian massages.',
    requirements: ['3+ years luxury spa experience', 'Massage therapy certification', 'English communication'],
    benefits: ['Accommodation negotiable', 'Medical insurance', 'Staff discounts'],
    visaSponsorship: true,
    accommodationProvided: false,
    urgent: false,
    verified: true,
    postedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    applicants: 18,
    views: 230,
    status: 'active',
    employerId: 'emp5',
  },
  {
    id: 'j6',
    title: 'Sous Chef – Italian Cuisine',
    hotelName: 'Crown Melbourne',
    hotelLogo: '🏨',
    country: 'au', countryLabel: 'Australia', countryFlag: '🇦🇺',
    city: 'Melbourne',
    department: 'Kitchen / Culinary',
    type: 'full-time',
    salary: { min: 4200, max: 5500, currency: 'USD', period: 'month' },
    experience: 'senior',
    hotel_category: '5-Star / Luxury',
    description: 'Support the Head Chef in managing Italian cuisine operations, mentoring junior staff, and maintaining authentic recipes.',
    requirements: ['5+ years culinary experience', 'Specialisation in Italian cuisine', 'Valid Australian work visa or sponsorship eligible'],
    benefits: ['Salary packaging available', 'Career progression', 'Staff restaurant'],
    visaSponsorship: true,
    accommodationProvided: false,
    urgent: false,
    verified: true,
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    applicants: 9,
    views: 190,
    status: 'active',
    employerId: 'emp6',
  },
];

export const MOCK_CANDIDATES = [
  {
    id: 'c1',
    displayName: 'Rajan Mehta',
    headline: 'Executive Chef | Luxury Hospitality | 14 Years',
    nationality: 'in', nationalityLabel: 'India', nationalityFlag: '🇮🇳',
    currentLocation: 'Mumbai, India',
    department: 'Kitchen / Culinary',
    experience: 'exec',
    experienceYears: 14,
    skills: ['HACCP', 'Menu Engineering', 'F&B Cost Control', 'Team Leadership', 'ISO 22000', 'Mixology', 'POS Systems'],
    certifications: ['HACCP Level 3', 'Culinary Arts Diploma', 'ISO 22000', 'Food Safety Level 4'],
    rating: 4.8,
    ratingCount: 23,
    videoProfile: true,
    profileStrength: 88,
    isOpenToWork: true,
    partTimeAvailable: true,
    linkedinURL: 'https://linkedin.com/in/rajanmehta',
    workHistory: [
      { role: 'Executive Chef', hotel: 'Oberoi Grand, Kolkata', period: '2020–Present', type: 'full-time' },
      { role: 'Sous Chef', hotel: 'ITC Maurya, New Delhi', period: '2016–2020', type: 'full-time' },
      { role: 'Chef de Partie', hotel: 'Marriott Maldives Resort', period: '2013–2016', type: 'full-time' },
    ],
    about: 'Award-winning Executive Chef with 14 years in luxury hospitality across India, UAE and Southeast Asia. Specialist in Indian, Pan-Asian and Continental cuisines. Managed teams of 40+ at 5-star properties. Passionate about farm-to-table philosophy and sustainable kitchen practices.',
    languages: ['English', 'Hindi', 'Marathi'],
    countriesWorked: 6,
  },
  {
    id: 'c2',
    displayName: 'Maria Santos',
    headline: 'F&B Manager | Resort Operations | 9 Years',
    nationality: 'ph', nationalityLabel: 'Philippines', nationalityFlag: '🇵🇭',
    currentLocation: 'Manila, Philippines',
    department: 'F&B Service',
    experience: 'senior',
    experienceYears: 9,
    skills: ['Food & Beverage Management', 'Revenue Management', 'HACCP', 'Team Training', 'Event Management'],
    rating: 4.5,
    ratingCount: 17,
    videoProfile: true,
    profileStrength: 92,
    isOpenToWork: true,
    partTimeAvailable: false,
  },
];

export const MOCK_APPLICATIONS = [
  { id: 'a1', jobId: 'j1', jobTitle: 'Executive Chef', hotelName: 'Burj Al Arab Jumeirah', country: '🇦🇪 UAE', status: 'interview', appliedAt: '2025-04-08', interviewDate: '2025-04-15', step: 3 },
  { id: 'a2', jobId: 'j2', jobTitle: 'F&B Manager', hotelName: 'Shangri-La Dhaka', country: '🇧🇩 Bangladesh', status: 'reviewed', appliedAt: '2025-04-10', step: 2 },
  { id: 'a3', jobId: 'j4', jobTitle: 'Head Chef', hotelName: 'Park Hyatt Maldives', country: '🇲🇻 Maldives', status: 'shortlisted', appliedAt: '2025-04-08', step: 2 },
  { id: 'a4', jobId: 'j5', jobTitle: 'Executive Chef', hotelName: 'Grand Hyatt Sydney', country: '🇦🇺 Australia', status: 'offer', appliedAt: '2025-04-05', offerExpiry: '2025-04-20', step: 4 },
];

export const MOCK_SHIFTS = [
  { id: 's1', role: 'Banquet Waiter', hotel: 'Leela Palace', city: 'Mumbai', time: '6PM–11PM', pay: 22, payPeriod: 'shift', urgent: true, shiftDate: new Date(Date.now() + 6 * 3600000).toISOString() },
  { id: 's2', role: 'Bartender', hotel: 'ITC Grand', city: 'Delhi', time: '8PM–2AM', pay: 28, payPeriod: 'shift', urgent: false, shiftDate: new Date(Date.now() + 8 * 3600000).toISOString() },
  { id: 's3', role: 'Event Server', hotel: 'Hyatt Regency', city: 'Dubai', time: '5PM–10PM', pay: 35, payPeriod: 'shift', urgent: true, shiftDate: new Date(Date.now() + 3 * 3600000).toISOString() },
];

export const STATUS_STEPS = {
  applied:     { step: 1, label: 'Applied',    color: 'navy' },
  reviewed:    { step: 2, label: 'Reviewed',   color: 'gold' },
  shortlisted: { step: 2, label: 'Shortlisted',color: 'green' },
  interview:   { step: 3, label: 'Interview',  color: 'purple' },
  offer:       { step: 4, label: 'Offer!',     color: 'green' },
  rejected:    { step: 0, label: 'Not Selected',color: 'red' },
};

export const KANBAN_STAGES = ['applied', 'reviewed', 'shortlisted', 'interview', 'offer'];
